project:
  type: website
  output-dir: docs
  resources:
    - assets/**/*
    - CNAME
    - .nojekyll
    - googlef48d8f5728f4a046.html
    - sitemap.xml

website:
  title: "Tulasimohan Molli"
  site-url: "https://tulasimohan.github.io"
  favicon: assets/images/TM_logo.png
  description: "Tulasimohan Molli's personal website"
  navbar:
    background: white
    pinned: true
    right:
      - href: index.qmd
        text: About
      - text: Publications 
        href: publications/publications.qmd
      - text: Teaching
        href: src/pages/teaching.qmd
      - text: Links
        href: src/pages/links.qmd
      - text: CV
        href: assets/pdf/Tulasi_s_Resume.pdf
  page-footer: 
    center: "Made with [Quarto](https://quarto.org) &#8729; h/t [Neeldhara Misra](https://www.neeldhara.com/)."
    right: 
      - text: "<img src='assets/images/github.svg' width='16' alt='GitHub'>"
        href: https://github.com/tulasimohan
      - text: "<img src='assets/images/linkedin.png' width='16' alt='LinkedIn'>"
        href: https://www.linkedin.com/in/tulasimohan-molli-b206b2164
      - text: "<img src='assets/images/mastodon.png' width='16' alt='Mastodon'>"
        href: https://mathstodon.xyz/@tulasimohan
      - text: "<img src='assets/images/bluesky.png' width='16' alt='Bluesky'>"
        href: https://bsky.app/profile/tulasimohan.bsky.social
      - text: "<img src='assets/images/dblp.png' width='16' alt='DBLP'>"
        href: https://dblp.org/pid/231/1775.html
      - text: "<img src='assets/images/ORCID.png' width='16' alt='ORCID'>"
        href: https://orcid.org/0000-0001-6683-9050
      - text: "<img src='assets/images/google_scholar.png' width='16' alt='Google Scholar'>"
        href: https://scholar.google.com/citations?user=_WTuVPIAAAAJ&hl=en
     

format:
  html:
    base-url: "/"
    theme: 
      light: [cosmo, assets/css/custom.scss]
    css: 
      - assets/css/styles.css
      - assets/css/fonts.css
    toc: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    page-layout: full
    include-in-header: googlef48d8f5728f4a046.html
    include-after-body: googlef48d8f5728f4a046.html
    mainfont: "IBM Plex Serif"
    monofont: "IBM Plex Mono"
    linkcolor: "#0077CC"

# Ensure the Google Search Console verification file and sitemap are included in the output
resources:
  - googlef48d8f5728f4a046.html
  - sitemap.xml
