project:
  type: website
  output-dir: docs

website:
  title: "Tulasimohan Molli"
  site-url: "https://tulasimohan.github.io"
  favicon: images/TM_logo.png
  description: "Tulasimohan Molli's personal website"
  navbar:
    background: white
    pinned: true
    right:
      - href: index.qmd
        text: About
      # - text: Research
      #   menu:
      - text: Publications 
        href: publications/publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: Tulasi_s_Resume.pdf
  page-footer: 
    center: "Made with [Quarto](https://quarto.org) &#8729; h/t [Neeldhara Misra](https://www.neeldhara.com/)."
    right: 
      - text: "<img src='images/github.svg' width='16' alt='GitHub'>"
        href: https://github.com/tulasimohan
      - text: "<img src='images/linkedin.png' width='16' alt='LinkedIn'>"
        href: https://www.linkedin.com/in/tulasimohan-molli-b206b2164
      - text: "<img src='images/mastodon.png' width='16' alt='Mastodon'>"
        href: https://mathstodon.xyz/@tulasimohan
      - text: "<img src='images/bluesky.png' width='16' alt='Bluesky'>"
        href: https://bsky.app/profile/tulasimohan.bsky.social
      - text: "<img src='images/dblp.png' width='16' alt='DBLP'>"
        href: https://dblp.org/pid/231/1775.html
      - text: "<img src='images/ORCID.png' width='16' alt='ORCID'>"
        href: https://orcid.org/0000-0001-6683-9050
      - text: "<img src='images/google_scholar.png' width='16' alt='Google Scholar'>"
        href: https://scholar.google.com/citations?user=_WTuVPIAAAAJ&hl=en
     

format:
  html:
    theme: 
      light: [cosmo, custom.scss] 
    css: css/styles.css
    toc: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    page-layout: full
    includes:
      in-header: googlef48d8f5728f4a046.html

# bibliography:
#   - zotero/My Library.bib
# Optionally, specify a citation style file (e.g., APA, MLA, etc.)
# csl: apa.csl
