site-url: "https://tulasimohan.github.io/Quarto-Homepage"
output-dir: docs

project:
  type: website

website:
  title: "Tulasimohan Molli"
  navbar:
    background: white
    pinned: true
    right:
      - href: about.qmd
        text: Home
      - text: Research
        menu:
          - text: Publications 
            href: publications/publications.qmd
          - text: Teaching
            href: teaching.qmd
  page-footer: 
    left: "&#169; 2025 Tulasimohan Molli"
    center: "Made with [Quarto](https://quarto.org) &#8729; h/t [Neeldhara Misra](https://www.neeldhara.com/)."
    right: 
      - icon: github
        href: https://github.com/tulasimohan
      - icon: linkedin
        href: https://www.linkedin.com/in/tulasimohan-molli-b206b2164
      - icon: mastodon
        href: https://mathstodon.xyz/@tulasimohan
      - icon: bluesky
        href: https://bsky.app/profile/tulasimohan.bsky.social

format:
  html:
    theme: 
      light: [cosmo, custom.scss] 
    css: css/styles.css
    toc: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    page-layout: full
