project:
  type: website

website:
  title: "Tulasimohan Molli"
  navbar:
    right:
      - icon: house-door
        href: index.qmd
        text: Home
      - icon : file-person
        href: about.qmd
        text: About
      - icon : book
        href: research.qmd
        text: Research
      - 
        text: Teaching
        href: teaching.qmd
format:
  html:
    theme: 
      light: sketchy
      dark: sketchy
    css: styles.css
    toc: false

