project:
  output-dir: tulasi_site
  type: website
  preview:
    port: 7777
  
website:
  title: "Tulasimohan Molli"
  navbar:
    background: white
    pinned: true
    right:
      - href: about.qmd
        text: About
      - text: Research
        menu:
          - text: Publications 
            href: publications/publications.qmd
          # - text: Informal
          #   href: notes.qmd 
          - text: Teaching
            href: teaching.qmd
      # - text: Misc.
      #   menu: 
      #     - href: portugal.qmd
      #       text: How to Portugal
  # sidebar:
  #   - text: "Data Structure LBs"
  #     contents: docs
  page-footer: 
    left: >-
      &#169; 2025 Tulasimohan Molli &#8729; Made with [Quarto](https://quarto.org)| h/t [Neeldhara's webpage](). 
    right: 
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com
      - icon: mastodon
        href: https://mathstodon.xyz/@neeldhara
      - icon: bluesky
        href: https://bsky.app/

format:
  html:
    theme: 
      light: [cosmo, custom.scss] 
    # js: scripts.js
    css: css/styles.css
    toc: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    # include-after-body: footer.html
    page-layout: full
