project:
  type: website

website:
  title: "Tulasimohan Molli"
  sidebar:
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - text: Teaching
        href: teaching.qmd
      - text: Misc.
        href: misc.qmd
format:
  html:
    theme: 
      light: [Sketchy,theme-light.scss]
      dark: [Sketchy, theme-dark.scss]
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/tex-gyre-adventor" type="text/css"/>
    css: styles.css
    mainfont: TeXGyreAdventorRegular